using RigidityTheoryTools
using Graphs
using LinearAlgebra
import Oscar
using Test

@testset "RigidityTheoryTools.jl" begin
    @testset "Infinitesimal Rigidity" begin
        # graph that is rigid but not infinitesimally rigid
        g = SimpleGraph(6)
        add_edge!(g, 1, 2)
        add_edge!(g, 2, 3)
        add_edge!(g, 3, 4)
        add_edge!(g, 1, 5)
        add_edge!(g, 4, 5)
        add_edge!(g, 1, 6)
        add_edge!(g, 4, 6)
        add_edge!(g, 5, 6)

        emb = [
            -1.5 1;
            -0.5 1;
            0.5 1;
            1.5 1;
            0 0;
            0 -1
        ]'

        f = Framework(g, emb)
        R = rigidity_matrix(f)

        @test !is_infrigid(f)
        @test LinearAlgebra.rank(R) == 7
    end
    @testset "Symmetric Rigidity" begin
        @testset "Quotient Gain Graph" begin
            g = SimpleGraph(6)
            add_edge!(g, 1, 2)
            add_edge!(g, 2, 3)
            add_edge!(g, 1, 3)
            add_edge!(g, 1, 4)
            add_edge!(g, 2, 5)
            add_edge!(g, 3, 6)
            add_edge!(g, 4, 5)
            add_edge!(g, 5, 6)
            add_edge!(g, 4, 6)

            G = Oscar.symmetric_group(6)
            H, _ = Oscar.sub(G, [Oscar.perm([2, 3, 1, 5, 6, 4])])

            qg = quotient_graph(g, H)
        end

        @testset "Orbit rigidity matrix" begin
            g = SimpleGraph(6)
            add_edge!(g, 1, 2)
            add_edge!(g, 2, 3)
            add_edge!(g, 1, 3)
            add_edge!(g, 1, 4)
            add_edge!(g, 2, 5)
            add_edge!(g, 3, 6)
            add_edge!(g, 4, 5)
            add_edge!(g, 5, 6)
            add_edge!(g, 4, 6)

            G = Oscar.symmetric_group(6)
            H, _ = Oscar.sub(G, [Oscar.perm([2, 3, 1, 5, 6, 4])]) # C3 subgroup of G

            qg = quotient_graph(g, H)

            # embedding of g with C3 symmetry
            p_reps = [
                cosd(120) sind(120);
                cosd(240) sind(240);
                cosd(0) sind(0);
                1.5*cosd(120) 1.5*sind(120);
                1.5*cosd(240) 1.5*sind(240);
                1.5*cosd(0) 1.5*sind(0)
            ]'
            f = Framework(g, p_reps)

            mat_group = RigidityTheoryTools.rotation_group_around_origin_2d(1 // 3) # rotation group around origin generated by rotation of angle 1/3*2π
            ord = Oscar.order(mat_group)
            repr = Oscar.hom(H, mat_group, Oscar.gens(H), Oscar.gens(mat_group)) # representation of H as matrix group

            @test RigidityTheoryTools.is_symmetric(f, repr)

            orbit_mat = orbit_rigidity_matrix(f, repr)

            @test LinearAlgebra.rank(orbit_mat) == 2
        end
    end
end

